name: publish
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: publish
        if: false
        run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: "https://maven.pkg.github.com/RelativityMC/intermediary/"
          MAVEN_CRED_USR: ${{ github.actor }}
          MAVEN_CRED_PSW: ${{ secrets.GITHUB_TOKEN }}

